var express = require('express');
var app = express();
var morgan = require('morgan');             // log requests to the console (express4)
var bodyParser = require('body-parser');    // pull information from HTML POST (express4)
//var methodOverride = require('method-override'); // simulate DELETE and PUT (express4)


/* models */
Clip = require("./models/clip.js")

app.use(express.static(__dirname + '/public'));                 // set the static files location /public/img will be /img for us
app.use(morgan('dev'));                                         // log every request to the console
 //   app.use(bodyParser.urlencoded({'extended':'true'}));            // parse application/x-www-form-urlencoded
 app.use(bodyParser.urlencoded({ extended: true }));
    app.use(bodyParser.json());                                     // parse application/json
    app.use(bodyParser.json({ type: 'application/vnd.api+json' })); // parse application/vnd.api+json as json
    //app.use(methodOverride());

var admin = require("firebase-admin");

//var serviceAccount = require("/Users/pederjonsson/Library/webb/igne-natura/igne-natura-firebase-adminsdk-kluso-c11ad60b78.json");
var serviceAccount = require("/Users/pederjonsson/web/igne-natura/igne-natura-firebase-adminsdk-kluso-c11ad60b78.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://igne-natura.firebaseio.com/"
});

var db = admin.database();
var clipsRef = db.ref("clips");

//var clipUrls = [];
//var count = 0;

/*ref.on("child_added", function(snap) {
  count++;
  console.log("added:", snap.key);
  var clip = new Clip(snap.val());
	  console.log("clip: " + clip.data.url);
	  clipUrls.push(clip.data.url);
});*/

// length will always equal count, since snap.val() will include every child_added event
// triggered before this point
/*ref.once("value", function(snap) {
  console.log("initial data loaded!", snap.numChildren() === count);
});*/

// routes ======================================================================

app.get('/', function(req, res) {
	console.log("loaded index page");
    res.sendfile('./public/index.html'); // load the single view file (angular will handle the page changes on the front-end)
});


app.get('/api/clips', function(req, res) {
	console.log("api clips here");

	clipsRef.once("value", function(snapshot) {
	  console.log(snapshot.val());
	  res.json(snapshot.val());
	});
});

app.post('/api/clip', function(req, res) {
 	console.log('req.body.minage: ' + req.body.minage);
 	console.log('req.body.violence: ' + req.body.violence);
 	console.log('req.body.url: ' + req.body.url);

 	var newPostRef = clipsRef.push();
	newPostRef.set({
	  minimumAge: req.body.minage,
	  violence: req.body.violence,
	  url: req.body.url
	});
	// Get the unique key generated by push()
	var postId = newPostRef.key;
	console.log(postId);

	clipsRef.once("value", function(snapshot) {
	  console.log(snapshot.val());
	  res.json(snapshot.val());
	});

   // res.end();
});

app.get('api/clip', function(req, res) {
 	console.log('Processing get request...');
    res.send("jippi");
});

app.delete('api/clip/:clip_id', function(req, res) {

	res.send("deleted clip id: " + req.params.clip_id);
	/*ref.once("value", function(snapshot) {
	  console.log(snapshot.val());
	  res.send(snapshot.val())
	});*/
});

app.listen(8080, function () {
  console.log('Example app listening on port 8080!')
})

